[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = true

[auth.sms]
enable_signup = false

[realtime]
enabled = true

[storage]
enabled = true
file_size_limit = "50MiB"

[db]
port = 54322
shadow_port = 54320
major_version = 15
